# Generated by Django 4.0.6 on 2022-07-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0002_remove_company_master_password_and_more'),
        ('ItemMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_master',
            name='company_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_master',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Arrving_Date', models.DateField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
                ('Warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.warehouse_master')),
            ],
        ),
    ]
