# Generated by Django 4.0.6 on 2022-08-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0002_remove_company_master_password_and_more'),
        ('ItemMaster', '0002_item_master_company_id_alter_item_master_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVOICE_MASTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(max_length=250)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceDueDate', models.DateField()),
                ('TotalAmount', models.IntegerField()),
                ('TotalTax', models.CharField(max_length=50)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=50)),
                ('ModifiedDate', models.DateField()),
                ('DealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.dealer_master')),
            ],
        ),
        migrations.CreateModel(
            name='INVOICE_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Rate', models.IntegerField(null=True)),
                ('ItemServiceNo', models.IntegerField(null=True)),
                ('Invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.invoice_master')),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemMaster.item_master')),
            ],
        ),
    ]
