# Generated by Django 4.0.6 on 2022-07-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=250)),
                ('GST_Number', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Email_Address', models.EmailField(max_length=250)),
                ('Phone_Number', models.IntegerField()),
                ('Office_Number', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_company_name', models.CharField(max_length=250)),
                ('dealre_name', models.CharField(max_length=250)),
                ('dealer_address', models.CharField(max_length=250)),
                ('gst_number', models.CharField(max_length=250)),
                ('dealer_email_address', models.CharField(max_length=250)),
                ('dealer_phone_number', models.CharField(max_length=250)),
                ('dealer_office_number', models.CharField(max_length=250)),
                ('IsDeleted', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=250)),
                ('CreatedDate', models.DateField()),
                ('ModifiedBy', models.CharField(max_length=250)),
                ('ModifiedDate', models.DateField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
    ]
