# Generated by Django 4.0.6 on 2022-07-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniQInvoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_master',
            name='password',
        ),
        migrations.AddField(
            model_name='company_master',
            name='Company_website',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_master',
            name='Owner_name',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer_master',
            name='IsDealer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='Email_Address',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer_master',
            name='gst_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Login_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.EmailField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniQInvoice.company_master')),
            ],
        ),
    ]
